### DISCUSSION TITLE
How to connect to remote Ollama server?

### DISCUSSION THREAD

**Discussion by olegshulyakov** [fmaclen/hollama#232] [Q&A] [answered]
I am using Hollama as a Docker service
```yaml
version: '3.4'
services:
  hollama:
    image: ghcr.io/fmaclen/hollama:latest
    container_name: hollama
    mem_limit: 2g
    healthcheck:
      test: curl -f http://localhost:4173 || exit 1
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '${ROOT}/docker/hollama:/app/backend/data'
    ports:
      - 4173:4173
    restart: unless-stopped
```
I have set `OLLAMA_HOST=0.0.0.0` on Ollama machine. It is working as a service there.
Open WebUI and Enchanced do work with that server, but I am not able to connect Hollama to it.

![image](https://github.com/user-attachments/assets/7e16bc3c-2299-40cb-bfef-5f6966a2895c)

What I am doing wrong?
