### ISSUE TITLE
LM Studio server not working

### ISSUE THREAD

**Issue by olegshulyakov** [fmaclen/hollama#295]
LM Studio server allows to run OpenAI-compatible endpoint, wanted to try it with Hollama, but faced an issue with setting up the connection.

**Steps to reproduce:**
1. Setup Hollama in Docker
```
services:
  hollama:
    image: ghcr.io/fmaclen/hollama:latest
    container_name: hollama
    restart: unless-stopped
    mem_limit: 256m
    healthcheck:
      test: curl -sS 127.0.0.1:4173 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - "${FOLDER_FOR_DATA}/hollama:/app/backend/data"
    ports:
      - 4173:4173
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - VITE_ALLOWED_HOSTS=${LOCAL_DOCKER_HOSTNAME}
```
2. Go to Hollama settings.
3. Select "OpenAI-compatible, ie llama.cpp" in Servers.
4. Press "Add Connection" button.
5. Set "Base URL" to "http://<server_ip>:1234/v1"
6. Press Verify button

**Actual:** "Get connection failed" message.
**Expected:** Connection succeded.

**Notes:**
- The issue is happening because Hollama sends wrong request to the Server API: it sends _OPTIONS /v1/models_ instead of _GET /v1/models_. So changing request type from **OPTIONS** to **GET** should fix this issue.
- LM Studio provides following [endpoints](https://lmstudio.ai/docs/app/api/endpoints/openai):
   - GET /v1/models
   - POST /v1/chat/completions
   - POST /v1/completions
   - POST /v1/embeddings
